language: python
python:
  - "2.7"
env:
    - DJANGO='django>=1.4,<1.5'
    - DJANGO='django>=1.5'
install:
  - pip install $DJANGO --use-mirrors
  - pip install -r requirements/develop.pip --use-mirrors
script: python manage.py test eztables
